### ISSUE TITLE
项目很好，但是配置过程太复杂了

### ISSUE THREAD

**Issue by Dannypung** [kingbase/zanki#2]
能否求一份Leetcode的apkg？anki对markdown的支持不是很好

**Comment by kingbase** [comment]
你可以试试这个，只导入了前200个题目
[leetcode.zip](https://github.com/kingbase/zanki/files/5644281/leetcode.zip)
但个人认为只有加入了自己的笔记，才能更好的学习题目。


> anki对markdown的支持不是很好

zanki 要解决的问题之一就是引入对 markdown 的支持。

**Comment by Dannypung** [comment]
感谢您的无私奉献，唯一的痛点就是anki里面插入代码块了，试了几种方法都不是很有效，我再尝试尝试。再次感谢，祝安~

发件人: Qin<mailto:notifications@github.com>
发送时间: 2020年12月5日 1:22
收件人: kingbase/zanki<mailto:zanki@noreply.github.com>
抄送: Dannypung<mailto:Dannypung@hotmail.com>; Author<mailto:author@noreply.github.com>
主题: Re: [kingbase/zanki] 项目很好，但是配置过程太复杂了 (#2)


你可以试试这个，只导入了前200个题目
leetcode.zip<https://github.com/kingbase/zanki/files/5644281/leetcode.zip>
但个人认为只有加入了自己的笔记，才能更好的学习题目。

anki对markdown的支持不是很好

zanki 要解决的问题之一就是引入对 markdown 的支持。

―

**Comment by kingbase** [comment]
> 唯一的痛点就是anki里面插入代码块了

这个问题可以查看下本项目的 readme，其中已经提到了：

> 添加自己的做题笔记到 output/raw/leetcode/my_solution 目录，文件名为[题号].md，见 repo 中的 5.md 作为示例，md 文件支持代码高亮和 Latex 公式。

刚才上传的 leetcode.zip 中的代码，也是直接由 leetcode 中文官网爬取的 markdown 文件生成和渲染的。
