### ISSUE TITLE
Android Anki兼容性测试

### ISSUE THREAD

**Issue by Dannypung** [kingbase/zanki#3]
MathJax Code格式在2.10.0版本以上才可渲染，请确保Android Anki软件版本更新。[https://github.com/ankidroid/Anki-Android/milestone/37](url)

**Comment by kingbase** [comment]
看了下这个链接：[Update AnkiDroid to Mathjax 3 by hgiesel · Pull Request #7782 · ankidroid/Anki-Android](https://github.com/ankidroid/Anki-Android/pull/7782)，其中提到的是：

> MathJax 3 uses localStorage to save user settings, which the user can change by right clicking the output (example). So while this error log is annoying, MathJax 3 still works without a hiccup.

也就是说虽然会报错，但不影响使用。或许低版本也跑得起来。
